# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aC-VOVn-vxDT-GuUcOoRDoLLJ7XyqYJ6
"""

import streamlit as st
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Model definition
class VAE(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 400)
        self.fc21 = nn.Linear(400, 20)
        self.fc22 = nn.Linear(400, 20)
        self.fc3 = nn.Linear(20, 400)
        self.fc4 = nn.Linear(400, 784)

    def encode(self, x):
        h1 = F.relu(self.fc1(x))
        return self.fc21(h1), self.fc22(h1)

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
        h3 = F.relu(self.fc3(z))
        return torch.sigmoid(self.fc4(h3))

    def forward(self, x):
        mu, logvar = self.encode(x.view(-1, 784))
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

# Load model
model = VAE()
model.load_state_dict(torch.load("vae_mnist.pth", map_location="cpu"))
model.eval()

# Streamlit UI
st.title("Handwritten Digit Generator")
st.write("Click the button to generate 5 random handwritten digits (not class-conditional)")

if st.button("Generate"):
    fig, axs = plt.subplots(1, 5, figsize=(10, 2))
    for i in range(5):
        z = torch.randn(1, 20)
        with torch.no_grad():
            sample = model.decode(z).view(28, 28).numpy()
        axs[i].imshow(sample, cmap='gray')
        axs[i].axis("off")
    st.pyplot(fig)

